services:
  fluent-cms:
    image: fluent-cms
    build:
      context: .
      dockerfile: FluentCMS/Dockerfile
    environment:
      - PgConnection=Host=fluent-cms-db;Port=5432;Database=fluent-cms;Username=postgres;Password=mysecretpassword
    ports:
      - "8080:8080"
  fluent-cms-db:
    image: postgres:latest
    container_name: fluent_cms_db_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: fluent-cms
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"